### ISSUE TITLE
Field for damage reduction?

### ISSUE THREAD

**Issue by rimbaum** [zsennenga/hades_save_editor#21]
I was wondering if there's a way to get in a field so we can change damage reduction. I'm maxed out and would like to actually reduce it for a mid-way challenge between god mode off and god mode maxed out. Even if it's just "reset god mode damage reduction" rather than entering a custom value, I'd super appreciate it.

**Comment by inspire22** [comment]
@zsennenga I also wanted this - I die too fast without any godmode, but it's up to like 45% now which feels too high.  I see you'd worked on this in November so was trying to build the latest version.  I got pyinstaller and pluto.ui installed OK but when I try to run the resulting main.exe I just get "failed to execute script main" - is this just because it's not building currently, or can you point me in a direction on how to resolve it please?

Thanks for a great project

**Comment by zsennenga** [comment]
Unfortunately, don't have any insight into your build errors, it's possible there's some implicit assumption on my part about my env here. That said, you don't need to compile it to run it, you can just run the python script if you have a dev environment for it. If this is a change already on master, I can push a binary sometime for that, if not, I probably won't go digging for it myself, but happy to accept a PR.

**Comment by zsennenga** [comment]
Build issues look to be due to a missing requirement in a merged pr. Probably. Try master now.

**Comment by zsennenga** [comment]
Also I uploaded a binary, so maybe just use that.

**Comment by inspire22** [comment]
Nice, thanks so much!
